In [ ]:
from google.colab import files
uploaded = files.upload()

Saving hw_200.csv to hw_200.csv

In [ ]:
import pandas as pd

df = pd.read_csv("hw_200.csv")

df.head()

   Index   Height(Inches)"   "Weight(Pounds)"
0      1             65.78             112.99
1      2             71.52             136.49
2      3             69.40             153.03
3      4             68.22             142.34
4      5             67.79             144.30

In [ ]:
df.info()
df.isna().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              200 non-null    int64
 1    Height(Inches)"   200 non-null    float64
 2    "Weight(Pounds)"  200 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 4.8 KB

            Index   Height(Inches)"   "Weight(Pounds)"
count  200.000000        200.000000         200.000000
mean   100.500000         67.949800         127.221950
std     57.879185          1.940363          11.960959
min      1.000000         63.430000          97.900000
25%     50.750000         66.522500         119.895000
50%    100.500000         67.935000         127.875000
75%    150.250000         69.202500         136.097500
max    200.000000         73.900000         158.960000

In [ ]:
# Remove duplicates
df = df.drop_duplicates()

# Handle missing values
for col in df.select_dtypes(include=['float64', 'int64']).columns:
    df[col].fillna(df[col].median(), inplace=True)

for col in df.select_dtypes(include=['object']).columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Standardize text
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].str.lower().str.strip()

# Save cleaned file
df.to_csv("cleaned_data.csv", index=False)

print("Task 1 Completed ✅")

Task 1 Completed ✅

/tmp/ipykernel_3320/2402666558.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [ ]:
files.download("cleaned_data.csv")